Enabled Podman build with UID 1000
When building the "build container image" using
"podman/redox-base-containerfile", the process will fail if host UID is
1000 due to it already existing by default in the base container image:

```
[...]

STEP 3/3: RUN useradd --create-home --no-log-init --uid 1000 poduser &&
chown -R root:root /home

useradd: UID 1000 is not unique

Error: error building at STEP "RUN useradd --create-home --no-log-init
--uid 1000 poduser && chown -R root:root /home":
error while running runtime: exit status 4
make: *** [mk/podman.mk:57: build/container.tag] Error 125
```

This commit deletes the default container image user "ubuntu" that
occupies UID 1000.