nix: Update rust-overlay
Fixes error when running nix develop .#native:

error: attribute '"2026-05-24"' missing
at /tryredox/redox/flake.nix:48:24:
48| rust-bin = pkgs.rust-bin.nightly."2026-05-24".default.override {

Introduced in a42a64e3.